<div class="content-intro"><h2><strong>About Anthropic</strong></h2>
<p>Anthropic’s mission is to create reliable, interpretable, and steerable AI systems. We want AI to be safe and beneficial for our users and for society as a whole. Our team is a quickly growing group of committed researchers, engineers, policy experts, and business leaders working together to build beneficial AI systems.</p></div><h2>About the Team</h2>
<p>As part of Anthropic's expanding Global Safety and Security team, the Security Operations Coordinator will serve as the primary point of contact for security operations across our EMEA region, including offices in London, Dublin, Zurich, and more to come. This unique position offers the opportunity to shape security operations for a rapidly growing AI company operating across multiple regulatory environments. You'll enhance our EMEA security posture by developing comprehensive operations plans, establishing emergency response protocols, and strengthening site security measures while ensuring compliance with varying European regulations. Building vital relationships with local site leadership, government agencies, and first responders across five countries, you'll ensure consistent security standards aligned with global practices while adapting to regional requirements.</p>
<h2>Responsibilities:</h2>
<ul>
<li>Develop and implement standardized security protocols across EMEA offices, ensuring alignment with global security standards while meeting varying European regulatory requirements</li>
<li>Evaluate potential office locations in EMEA from a security risk perspective and develop comprehensive security plans for new buildouts</li>
<li>Collaborate with architects, construction teams, and facilities on security design integration for new office locations, navigating different European building codes and standards</li>
<li>Establish and maintain partnerships with local site leadership teams across all EMEA locations, providing guidance on security best practices and emergency response procedures</li>
<li>Coordinate with on-site security personnel and contracted security providers to maintain consistent protection standards and operational excellence across EMEA</li>
<li>Build relationships with local emergency responders, law enforcement, and government security agencies across EMEA, coordinating response protocols</li>
<li>Develop and implement emergency preparedness programs tailored to each location's unique needs, risk profile, and regulatory requirements</li>
<li>Ensure physical security systems and operations comply with local requirements across all EMEA locations</li>
<li>Travel regularly across EMEA locations (approximately 25%) to maintain operational oversight and stakeholder relationships</li>
</ul>
<h2>You may be a good fit if you have:</h2>
<ul>
<li>5+ years of progressive experience in security operations, with demonstrated expertise in coordinating security programs across multiple locations in Europe</li>
<li>Experience evaluating security requirements for potential office locations in multiple European countries and developing comprehensive security plans for new buildouts</li>
<li>Background in collaborating with design and construction teams to integrate security elements into new facilities within varying European regulatory frameworks</li>
<li>Strong experience in developing and implementing physical security protocols, emergency response procedures, and business continuity plans across multiple European countries</li>
<li>Proven track record of building effective partnerships with stakeholders at all levels, including executive leadership, site managers, government agencies, and external partners across different cultures</li>
<li>Excellent project management skills with ability to drive multiple concurrent initiatives across countries while maintaining focus on day-to-day operations</li>
<li>Deep understanding of security technology systems, access control procedures, and industry best practices for facility protection in Europe</li>
<li>Based in or willing to relocate to London, with comfort traveling regularly across EMEA offices (approximately 25% travel)</li>
<li>Ability to work effectively across language barriers (multilingual capabilities strongly preferred)</li>
</ul>
<h2>Strong candidates may have:</h2>
<ul>
<li>Previous experience in technology company security operations or managing security programs for high-profile corporate environments across multiple European countries</li>
<li>Professional security certifications such as CPP, PSP, or relevant European industry credentials</li>
<li>Experience working with law enforcement and emergency services in multiple European countries</li>
<li>Understanding of European privacy regulations and their country-specific implementations</li>
<li>Language proficiency in German, French, or other European languages</li>
</ul>
<p><strong>Deadline to apply:&nbsp;</strong>None. Applications will be reviewed on a rolling basis.&nbsp;</p><div class="content-pay-transparency"><div class="pay-input"><div class="description"><p>The annual compensation range for this role is below. For sales roles, the range provided is the role’s On Target Earnings ("OTE") range, meaning that the range includes both the sales commissions/sales bonuses target and annual base salary for the role. Our total compensation package for full-time employees includes equity and benefits.</p></div><div class="title">Annual Salary:</div><div class="pay-range"><span>£105,000</span><span class="divider">&mdash;</span><span>£140,000 GBP</span></div></div></div><div class="content-conclusion"><h2><strong>Logistics</strong></h2>
<p><strong>Education requirements: </strong>We require at least a Bachelor's degree in a related field or equivalent experience.<strong><br><br>Location-based hybrid policy:</strong> Currently, we expect all staff to be in one of our offices at least 25% of the time. However, some roles may require more time in our offices.</p>
<p><strong data-stringify-type="bold">Visa sponsorship:</strong>&nbsp;We do sponsor visas! However, we aren't able to successfully sponsor visas for every role and every candidate. But if we make you an offer, we will make every reasonable effort to get you a visa, and we retain an immigration lawyer to help with this.</p>
<p><strong>We encourage you to apply even if you do not believe you meet every single qualification.</strong> Not all strong candidates will meet every single qualification as listed.&nbsp; Research shows that people who identify as being from underrepresented groups are more prone to experiencing imposter syndrome and doubting the strength of their candidacy, so we urge you not to exclude yourself prematurely and to submit an application if you're interested in this work. We think AI systems like the ones we're building have enormous social and ethical implications. We think this makes representation even more important, and we strive to include a range of diverse perspectives on our team.<br><br><strong data-stringify-type="bold">Your safety matters to us.</strong>&nbsp;To protect yourself from potential scams, remember that Anthropic recruiters only contact you from&nbsp;@anthropic.com&nbsp;email addresses. Be cautious of emails from other domains. Legitimate Anthropic recruiters will never ask for money, fees, or banking information before your first day. If you're ever unsure about a communication, don't click any links—visit&nbsp;<u data-stringify-type="underline"><a class="c-link c-link--underline" href="http://anthropic.com/careers" target="_blank" data-stringify-link="http://anthropic.com/careers" data-sk="tooltip_parent" data-remove-tab-index="true">anthropic.com/careers</a></u>&nbsp;directly for confirmed position openings.</p>
<h2><strong>How we're different</strong></h2>
<p>We believe that the highest-impact AI research will be big science. At Anthropic we work as a single cohesive team on just a few large-scale research efforts. And we value impact — advancing our long-term goals of steerable, trustworthy AI — rather than work on smaller and more specific puzzles. We view AI research as an empirical science, which has as much in common with physics and biology as with traditional efforts in computer science. We're an extremely collaborative group, and we host frequent research discussions to ensure that we are pursuing the highest-impact work at any given time. As such, we greatly value communication skills.</p>
<p>The easiest way to understand our research directions is to read our recent research. This research continues many of the directions our team worked on prior to Anthropic, including: GPT-3, Circuit-Based Interpretability, Multimodal Neurons, Scaling Laws, AI &amp; Compute, Concrete Problems in AI Safety, and Learning from Human Preferences.</p>
<h2><strong>Come work with us!</strong></h2>
<p>Anthropic is a public benefit corporation headquartered in San Francisco. We offer competitive compensation and benefits, optional equity donation matching, generous vacation and parental leave, flexible working hours, and a lovely office space in which to collaborate with colleagues. <strong data-stringify-type="bold">Guidance on Candidates' AI Usage:</strong>&nbsp;Learn about&nbsp;<a class="c-link" href="https://www.anthropic.com/candidate-ai-guidance" target="_blank" data-stringify-link="https://www.anthropic.com/candidate-ai-guidance" data-sk="tooltip_parent">our policy</a>&nbsp;for using AI in our application process</p></div>