<div class="content-intro"><h2><strong>About Anthropic</strong></h2>
<p>Anthropic’s mission is to create reliable, interpretable, and steerable AI systems. We want AI to be safe and beneficial for our users and for society as a whole. Our team is a quickly growing group of committed researchers, engineers, policy experts, and business leaders working together to build beneficial AI systems.</p></div><h2><strong>About the role:</strong></h2>
<p>We are seeking a Variable Compensation Leader to join our Finance team and play a pivotal role in shaping our compensation strategy for the Sales organization. In this strategic position, you will be a key leader within our go-to-market Finance team, working closely with the senior leaders across finance, revops and sales to design incentive compensation structures that align seller&nbsp; behavior with strategy and goals of the business. This role is critical to ensure Anthropic attracts top talent by establishing competitive incentives and rewards programs.&nbsp;</p>
<p>As our Finance Variable Compensation Lead, you will serve as the financial anchor developing strategic frameworks, and partnering with executive leadership &amp; revops compensation partners to gain alignment on compensation plans. In addition, you’ll work with Ops teams to ensure accurate reporting is in place to validate payouts and track data needed to understand the effectiveness of the comp plans. This role combines strategic finance and operational excellence to support our mission of developing safe and beneficial AI systems.</p>
<h2><strong>Responsibilities:&nbsp;</strong></h2>
<ul>
<li>Design comprehensive variable compensation strategies that align with Anthropic's business objectives, values, and growth trajectory</li>
<li>Partner with executive leadership to gain alignment on plan design principles, structures, and payout methodologies</li>
<li>Work with compensation team to analyze market trends and compensation data to ensure our programs remain competitive and effective</li>
<li>Establish budgeting processes and expense forecasting models tied to compensation</li>
<li>Partner with RevOps team to validate quota and attainment calculations</li>
<li>Prepare and deliver clear, concise, and insightful financial reports, analyses, and forecasts, highlighting key trends, risks, and opportunities to facilitate informed decision-making to stakeholders and executives</li>
<li>Collaborate with other members of strategic finance, FP&amp;A, and accounting counterparts, helping to align compensation proposals with broader financial strategies and priorities</li>
</ul>
<h2><strong>You may be a good fit if you have:</strong></h2>
<ul>
<li>Have 10+ years of experience in variable compensation design, administration, or related field, preferably in high-growth technology companies</li>
<li>Have deep expertise in GTM incentive plan design principles, including sales compensation, executive incentives, and broad-based variable pay programs</li>
<li>Are skilled at translating business strategy into actionable compensation frameworks that drive desired behaviors</li>
<li>Comfort working cross-functionally and are adept at communicating complex financial information to non-finance audiences</li>
<li>Excitement about working in a fast paced, dynamic environment and adapt well to change</li>
<li>Possess a bias towards action, strong work ethic, and have experience driving operational outcomes under tight timelines</li>
<li>Strong relationship building, business judgment, process management, and communication skills</li>
<li>Are passionate about Anthropic's mission to build safe, transformative AI systems</li>
</ul>
<h2><strong>Strong candidates may also have:&nbsp;</strong></h2>
<ul>
<li>Experience building variable compensation programs from the ground up in startup or scale-up environments</li>
<li>Familiarity with international compensation considerations for global teams</li>
<li>Understanding of AI/technology industry compensation trends and practices</li>
</ul>
<h2><strong>Logistics:</strong></h2>
<ul>
<li>Education requirements: We require at least a Bachelor's degree in a related field or equivalent experience.</li>
<li>Location-based hybrid policy: This role is based in the San Francisco office with a hybrid work model requiring 3 days in the office per week. We offer relocation assistance to new employees.</li>
<li>Visa sponsorship: We do sponsor visas! However, we aren't able to successfully sponsor visas for every role and every candidate. But if we make you an offer, we will make every reasonable effort to get you a visa, and we retain an immigration lawyer to help with this.</li>
</ul>
<p>We encourage you to apply even if you do not believe you meet every single qualification. Not all strong candidates will meet every single qualification as listed. Research shows that people who identify as being from underrepresented groups are more prone to experiencing imposter syndrome and doubting the strength of their candidacy, so we urge you not to exclude yourself prematurely and to submit an application if you're interested in this work. We think AI systems like the ones we're building have enormous social and ethical implications. We think this makes representation even more important, and we strive to include a range of diverse perspectives on our team.</p><div class="content-pay-transparency"><div class="pay-input"><div class="description"><p>The annual compensation range for this role is below. For sales roles, the range provided is the role’s On Target Earnings ("OTE") range, meaning that the range includes both the sales commissions/sales bonuses target and annual base salary for the role. Our total compensation package for full-time employees includes equity and benefits.</p></div><div class="title">Annual Salary:</div><div class="pay-range"><span>$235,000</span><span class="divider">&mdash;</span><span>$310,000 USD</span></div></div></div><div class="content-conclusion"><h2><strong>Logistics</strong></h2>
<p><strong>Education requirements: </strong>We require at least a Bachelor's degree in a related field or equivalent experience.<strong><br><br>Location-based hybrid policy:</strong> Currently, we expect all staff to be in one of our offices at least 25% of the time. However, some roles may require more time in our offices.</p>
<p><strong data-stringify-type="bold">Visa sponsorship:</strong>&nbsp;We do sponsor visas! However, we aren't able to successfully sponsor visas for every role and every candidate. But if we make you an offer, we will make every reasonable effort to get you a visa, and we retain an immigration lawyer to help with this.</p>
<p><strong>We encourage you to apply even if you do not believe you meet every single qualification.</strong> Not all strong candidates will meet every single qualification as listed.&nbsp; Research shows that people who identify as being from underrepresented groups are more prone to experiencing imposter syndrome and doubting the strength of their candidacy, so we urge you not to exclude yourself prematurely and to submit an application if you're interested in this work. We think AI systems like the ones we're building have enormous social and ethical implications. We think this makes representation even more important, and we strive to include a range of diverse perspectives on our team.<br><br><strong data-stringify-type="bold">Your safety matters to us.</strong>&nbsp;To protect yourself from potential scams, remember that Anthropic recruiters only contact you from&nbsp;@anthropic.com&nbsp;email addresses. Be cautious of emails from other domains. Legitimate Anthropic recruiters will never ask for money, fees, or banking information before your first day. If you're ever unsure about a communication, don't click any links—visit&nbsp;<u data-stringify-type="underline"><a class="c-link c-link--underline" href="http://anthropic.com/careers" target="_blank" data-stringify-link="http://anthropic.com/careers" data-sk="tooltip_parent" data-remove-tab-index="true">anthropic.com/careers</a></u>&nbsp;directly for confirmed position openings.</p>
<h2><strong>How we're different</strong></h2>
<p>We believe that the highest-impact AI research will be big science. At Anthropic we work as a single cohesive team on just a few large-scale research efforts. And we value impact — advancing our long-term goals of steerable, trustworthy AI — rather than work on smaller and more specific puzzles. We view AI research as an empirical science, which has as much in common with physics and biology as with traditional efforts in computer science. We're an extremely collaborative group, and we host frequent research discussions to ensure that we are pursuing the highest-impact work at any given time. As such, we greatly value communication skills.</p>
<p>The easiest way to understand our research directions is to read our recent research. This research continues many of the directions our team worked on prior to Anthropic, including: GPT-3, Circuit-Based Interpretability, Multimodal Neurons, Scaling Laws, AI &amp; Compute, Concrete Problems in AI Safety, and Learning from Human Preferences.</p>
<h2><strong>Come work with us!</strong></h2>
<p>Anthropic is a public benefit corporation headquartered in San Francisco. We offer competitive compensation and benefits, optional equity donation matching, generous vacation and parental leave, flexible working hours, and a lovely office space in which to collaborate with colleagues. <strong data-stringify-type="bold">Guidance on Candidates' AI Usage:</strong>&nbsp;Learn about&nbsp;<a class="c-link" href="https://www.anthropic.com/candidate-ai-guidance" target="_blank" data-stringify-link="https://www.anthropic.com/candidate-ai-guidance" data-sk="tooltip_parent">our policy</a>&nbsp;for using AI in our application process</p></div>