<div class="content-intro"><h2><strong>About Anthropic</strong></h2>
<p>Anthropic’s mission is to create reliable, interpretable, and steerable AI systems. We want AI to be safe and beneficial for our users and for society as a whole. Our team is a quickly growing group of committed researchers, engineers, policy experts, and business leaders working together to build beneficial AI systems.</p></div><h2><strong>About the role:</strong></h2>
<p>As a Recruiting Coordinator at Anthropic, you'll be the engine that helps our recruiting efforts go, helping to schedule onsite interviews and moving candidates through the pipeline. As the first point of contact for many candidates, you'll help ensure new potential recruits have a positive experience with us. You'll play a key role in helping Anthropic assemble a talented staff to help us build reliable, interpretable and steerable AI systems. In collaboration with our recruiting team, you'll continuously improve our recruitment processes and candidate experience.</p>
<h2>Responsibilities:</h2>
<ul>
<li>In partnership with our recruiters, regularly schedule a high volume of candidate interviews, debriefs, and reference checks. Navigate complex scheduling scenarios to coordinate availability across multiple stakeholders</li>
<li>Act as the primary point of contact for candidates, communicating externally with a warm and informative tone to provide a high-touch candidate experience. Ensure candidates feel supported and informed throughout their journey</li>
<li>Support and suggest improvements to our recruitment processes in collaboration with other team members in often ambiguous situations. Identify opportunities to enhance efficiency and candidate satisfaction</li>
<li>Drive the creation and implementation of new candidate experience programs and recruitment initiatives that enhance Anthropic's talent acquisition efforts and support the company's scaling hiring needs.</li>
</ul>
<h2>You may be a good fit if you have:</h2>
<ul>
<li>2+ years of experience in a high volume scheduling role, preferably in a recruiting or talent acquisition environment</li>
<li>A passion for creating an exceptional candidate and hiring manager experience</li>
<li>Excellent communication skills, especially a knack for writing friendly, informative emails that build rapport and convey information clearly</li>
<li>The ability to excel in a fast-paced environment, where you are frequently responding to questions, requests, or other new action items</li>
<li>A love of feedback and comfort both requesting and providing feedback to your colleagues</li>
<li>Proactive problem-solving skills in ambiguous situations with the ability to quickly generate multiple potential solutions to challenging problems</li>
<li>Experience acting as a strategic partner to Recruiters, helping them see around corners and suggesting improvements to their processes</li>
<li>An interest in Anthropic's mission and our deep commitment to AI safety in research and product development</li>
<li>Are fluent in Japanese and/or Korean &amp; English (native or business-level proficiency strongly preferred)</li>
</ul>
<p>The expected&nbsp;base compensation for this position is below. Our total compensation package for full-time employees includes equity, benefits, and may include incentive compensation.</p>
<h2>Compensation:</h2>
<ul>
<li>Base Pay: 11,020,800 JPY</li>
</ul><div class="content-conclusion"><h2><strong>Logistics</strong></h2>
<p><strong>Education requirements: </strong>We require at least a Bachelor's degree in a related field or equivalent experience.<strong><br><br>Location-based hybrid policy:</strong> Currently, we expect all staff to be in one of our offices at least 25% of the time. However, some roles may require more time in our offices.</p>
<p><strong data-stringify-type="bold">Visa sponsorship:</strong>&nbsp;We do sponsor visas! However, we aren't able to successfully sponsor visas for every role and every candidate. But if we make you an offer, we will make every reasonable effort to get you a visa, and we retain an immigration lawyer to help with this.</p>
<p><strong>We encourage you to apply even if you do not believe you meet every single qualification.</strong> Not all strong candidates will meet every single qualification as listed.&nbsp; Research shows that people who identify as being from underrepresented groups are more prone to experiencing imposter syndrome and doubting the strength of their candidacy, so we urge you not to exclude yourself prematurely and to submit an application if you're interested in this work. We think AI systems like the ones we're building have enormous social and ethical implications. We think this makes representation even more important, and we strive to include a range of diverse perspectives on our team.<br><br><strong data-stringify-type="bold">Your safety matters to us.</strong>&nbsp;To protect yourself from potential scams, remember that Anthropic recruiters only contact you from&nbsp;@anthropic.com&nbsp;email addresses. Be cautious of emails from other domains. Legitimate Anthropic recruiters will never ask for money, fees, or banking information before your first day. If you're ever unsure about a communication, don't click any links—visit&nbsp;<u data-stringify-type="underline"><a class="c-link c-link--underline" href="http://anthropic.com/careers" target="_blank" data-stringify-link="http://anthropic.com/careers" data-sk="tooltip_parent" data-remove-tab-index="true">anthropic.com/careers</a></u>&nbsp;directly for confirmed position openings.</p>
<h2><strong>How we're different</strong></h2>
<p>We believe that the highest-impact AI research will be big science. At Anthropic we work as a single cohesive team on just a few large-scale research efforts. And we value impact — advancing our long-term goals of steerable, trustworthy AI — rather than work on smaller and more specific puzzles. We view AI research as an empirical science, which has as much in common with physics and biology as with traditional efforts in computer science. We're an extremely collaborative group, and we host frequent research discussions to ensure that we are pursuing the highest-impact work at any given time. As such, we greatly value communication skills.</p>
<p>The easiest way to understand our research directions is to read our recent research. This research continues many of the directions our team worked on prior to Anthropic, including: GPT-3, Circuit-Based Interpretability, Multimodal Neurons, Scaling Laws, AI &amp; Compute, Concrete Problems in AI Safety, and Learning from Human Preferences.</p>
<h2><strong>Come work with us!</strong></h2>
<p>Anthropic is a public benefit corporation headquartered in San Francisco. We offer competitive compensation and benefits, optional equity donation matching, generous vacation and parental leave, flexible working hours, and a lovely office space in which to collaborate with colleagues. <strong data-stringify-type="bold">Guidance on Candidates' AI Usage:</strong>&nbsp;Learn about&nbsp;<a class="c-link" href="https://www.anthropic.com/candidate-ai-guidance" target="_blank" data-stringify-link="https://www.anthropic.com/candidate-ai-guidance" data-sk="tooltip_parent">our policy</a>&nbsp;for using AI in our application process</p></div>