<div class="content-intro"><h2><strong>About Anthropic</strong></h2>
<p>Anthropic’s mission is to create reliable, interpretable, and steerable AI systems. We want AI to be safe and beneficial for our users and for society as a whole. Our team is a quickly growing group of committed researchers, engineers, policy experts, and business leaders working together to build beneficial AI systems.</p></div><h2>About the Role:</h2>
<p>We're looking for the first Solutions Architect to join our Beneficial Deployments Applied AI team. You'll help mission-driven organizations—nonprofits, NGOs, foundations, and social enterprises—transform their operations and build impactful solutions with Claude.</p>
<p>This role combines technical expertise with deep relationship-building to help partners in education, global health, economic mobility, and life sciences accelerate their impact through AI adoption and deployment. You'll be the primary technical advisor for partners across segments, driving engagements from discovery through deployment, and coordinating with segment leads and product engineers to deliver impact.</p>
<h2>Responsibilities:</h2>
<ul>
<li>Serve as the primary technical advisor to mission-driven organizations throughout their Claude adoption journey—partnering with segment leads to understand requirements and translating them into impactful solutions from discovery through deployment</li>
<li>Transform partners into AI-native organizations through Claude Code enablement and internal business process evolution, to empower them to operate more effectively and build for where AI capabilities are headed</li>
<li>Design and lead cohort-based accelerators to scale our expertise and impact to multiple organizations simultaneously</li>
<li>Identify patterns across partners and segments to inform what we build at the ecosystem level—MCPs, evals, and other cross-partnership infrastructure</li>
<li>Create technical presentations, demos, and scalable technical content (documentation, tutorials, sample code) to accelerate partner adoption and self-service</li>
<li>Travel occasionally to customer sites for workshops, technical deep dives, and relationship building</li>
<li>Help shape team processes and culture as we scale from 1 to N</li>
</ul>
<h2>You Might Be a Good Fit If You Have:</h2>
<ul>
<li>3+ years in technical role, ideally with customer-facing exposure (Solutions Architect, Customer Engineer, Sales Engineer, Technical Account Manager, Product Engineer)</li>
<li>Experience working in or building trust with education, healthcare, scientific research, nonprofit, or other mission-driven organizations, understanding their unique challenges and constraints</li>
<li>Familiarity with common LLM implementation patterns, prompt engineering, evaluation frameworks, agent frameworks, and retrieval frameworks</li>
<li>A love of teaching, mentoring, and helping others succeed</li>
<li>A scrappy mentality–comfortable wearing multiple hats, building from scratch, driving clarity in ambiguous situations, and doing whatever it takes to further the mission</li>
</ul><div class="content-pay-transparency"><div class="pay-input"><div class="description"><p>The annual compensation range for this role is below. For sales roles, the range provided is the role’s On Target Earnings ("OTE") range, meaning that the range includes both the sales commissions/sales bonuses target and annual base salary for the role. Our total compensation package for full-time employees includes equity and benefits.</p></div><div class="title">Annual Salary:</div><div class="pay-range"><span>$240,000</span><span class="divider">&mdash;</span><span>$270,000 USD</span></div></div></div><div class="content-conclusion"><h2><strong>Logistics</strong></h2>
<p><strong>Education requirements: </strong>We require at least a Bachelor's degree in a related field or equivalent experience.<strong><br><br>Location-based hybrid policy:</strong> Currently, we expect all staff to be in one of our offices at least 25% of the time. However, some roles may require more time in our offices.</p>
<p><strong data-stringify-type="bold">Visa sponsorship:</strong>&nbsp;We do sponsor visas! However, we aren't able to successfully sponsor visas for every role and every candidate. But if we make you an offer, we will make every reasonable effort to get you a visa, and we retain an immigration lawyer to help with this.</p>
<p><strong>We encourage you to apply even if you do not believe you meet every single qualification.</strong> Not all strong candidates will meet every single qualification as listed.&nbsp; Research shows that people who identify as being from underrepresented groups are more prone to experiencing imposter syndrome and doubting the strength of their candidacy, so we urge you not to exclude yourself prematurely and to submit an application if you're interested in this work. We think AI systems like the ones we're building have enormous social and ethical implications. We think this makes representation even more important, and we strive to include a range of diverse perspectives on our team.<br><br><strong data-stringify-type="bold">Your safety matters to us.</strong>&nbsp;To protect yourself from potential scams, remember that Anthropic recruiters only contact you from&nbsp;@anthropic.com&nbsp;email addresses. Be cautious of emails from other domains. Legitimate Anthropic recruiters will never ask for money, fees, or banking information before your first day. If you're ever unsure about a communication, don't click any links—visit&nbsp;<u data-stringify-type="underline"><a class="c-link c-link--underline" href="http://anthropic.com/careers" target="_blank" data-stringify-link="http://anthropic.com/careers" data-sk="tooltip_parent" data-remove-tab-index="true">anthropic.com/careers</a></u>&nbsp;directly for confirmed position openings.</p>
<h2><strong>How we're different</strong></h2>
<p>We believe that the highest-impact AI research will be big science. At Anthropic we work as a single cohesive team on just a few large-scale research efforts. And we value impact — advancing our long-term goals of steerable, trustworthy AI — rather than work on smaller and more specific puzzles. We view AI research as an empirical science, which has as much in common with physics and biology as with traditional efforts in computer science. We're an extremely collaborative group, and we host frequent research discussions to ensure that we are pursuing the highest-impact work at any given time. As such, we greatly value communication skills.</p>
<p>The easiest way to understand our research directions is to read our recent research. This research continues many of the directions our team worked on prior to Anthropic, including: GPT-3, Circuit-Based Interpretability, Multimodal Neurons, Scaling Laws, AI &amp; Compute, Concrete Problems in AI Safety, and Learning from Human Preferences.</p>
<h2><strong>Come work with us!</strong></h2>
<p>Anthropic is a public benefit corporation headquartered in San Francisco. We offer competitive compensation and benefits, optional equity donation matching, generous vacation and parental leave, flexible working hours, and a lovely office space in which to collaborate with colleagues. <strong data-stringify-type="bold">Guidance on Candidates' AI Usage:</strong>&nbsp;Learn about&nbsp;<a class="c-link" href="https://www.anthropic.com/candidate-ai-guidance" target="_blank" data-stringify-link="https://www.anthropic.com/candidate-ai-guidance" data-sk="tooltip_parent">our policy</a>&nbsp;for using AI in our application process</p></div>