<div class="content-intro"><h2><strong>About Anthropic</strong></h2>
<p>Anthropic’s mission is to create reliable, interpretable, and steerable AI systems. We want AI to be safe and beneficial for our users and for society as a whole. Our team is a quickly growing group of committed researchers, engineers, policy experts, and business leaders working together to build beneficial AI systems.</p></div><p>As an Account Executive focused on Investment Banking &amp; Capital Markets at Anthropic, you'll be part of the foundational team bringing frontier AI to one of the most complex and high-stakes sectors in finance. You'll drive adoption of Claude across investment banks, capital markets firms, asset managers, and sell-side research institutions—helping them transform workflows in deal execution, research production, trading operations, and client advisory.</p>
<p>You'll leverage deep consultative sales expertise and sector knowledge to secure strategic enterprise deals while becoming a trusted partner to stakeholders navigating AI deployment in highly regulated environments. In collaboration with GTM, Product, Policy, and Marketing teams, you'll shape our approach to this critical vertical and help define how AI transforms capital markets.</p>
<p><strong>Responsibilities:</strong></p>
<ul>
<li>Own the full sales cycle from prospecting through close, winning new business and driving revenue within investment banking and capital markets accounts. Navigate complex organizational structures to reach decision-makers across front office, middle office, and technology functions.</li>
<li>Design and execute sales strategies tailored to the unique procurement dynamics, budget cycles, and risk considerations of capital markets institutions. Translate market intelligence into targeted account plans and campaigns.</li>
<li>Identify and develop new use cases across investment banking workflows—M&amp;A analysis, equity research, fixed income trading, compliance, and client reporting—collaborating cross-functionally to differentiate our offerings.</li>
<li>Build consensus across complex stakeholder ecosystems including Managing Directors, technology leadership, risk and compliance officers, and procurement teams.</li>
<li>Serve as the voice of the customer internally, gathering feedback from users and conveying market needs to inform product roadmaps, security requirements, and go-to-market positioning.</li>
<li>Contribute to the evolution of our financial services sales methodology by documenting learnings, refining playbooks, and identifying process improvements that drive productivity and consistency.</li>
</ul>
<p>You may be a good fit if you have:</p>
<ul>
<li>7+ years of enterprise B2B sales experience, with significant time selling into investment banks, capital markets firms, or asset managers</li>
<li>A track record of closing complex, six- and seven-figure deals within financial institutions by navigating both technical requirements and business use cases</li>
<li>Deep familiarity with how investment banks and capital markets firms buy technology—including vendor risk assessments, security reviews, and multi-stakeholder approval processes</li>
<li>Experience negotiating enterprise agreements within financial services procurement frameworks, including navigating legal, compliance, and infosec requirements</li>
<li>Proven history of exceeding revenue targets by effectively managing pipeline and executing a disciplined sales process</li>
<li>Strong executive presence and the ability to present confidently to audiences ranging from analysts and associates to C-suite executives</li>
<li>Understanding of investment banking and capital markets workflows, pain points, and competitive dynamics</li>
<li>A strategic, analytical mindset combined with creative tactical execution</li>
<li>Genuine enthusiasm for AI and its potential to transform financial services, paired with appreciation for the importance of safe and responsible deployment</li>
</ul><div class="content-pay-transparency"><div class="pay-input"><div class="description"><p>The annual compensation range for this role is below. For sales roles, the range provided is the role’s On Target Earnings ("OTE") range, meaning that the range includes both the sales commissions/sales bonuses target and annual base salary for the role. Our total compensation package for full-time employees includes equity and benefits.</p></div><div class="title">Annual Salary:</div><div class="pay-range"><span>$290,000</span><span class="divider">&mdash;</span><span>$435,000 USD</span></div></div></div><div class="content-conclusion"><h2><strong>Logistics</strong></h2>
<p><strong>Education requirements: </strong>We require at least a Bachelor's degree in a related field or equivalent experience.<strong><br><br>Location-based hybrid policy:</strong> Currently, we expect all staff to be in one of our offices at least 25% of the time. However, some roles may require more time in our offices.</p>
<p><strong data-stringify-type="bold">Visa sponsorship:</strong>&nbsp;We do sponsor visas! However, we aren't able to successfully sponsor visas for every role and every candidate. But if we make you an offer, we will make every reasonable effort to get you a visa, and we retain an immigration lawyer to help with this.</p>
<p><strong>We encourage you to apply even if you do not believe you meet every single qualification.</strong> Not all strong candidates will meet every single qualification as listed.&nbsp; Research shows that people who identify as being from underrepresented groups are more prone to experiencing imposter syndrome and doubting the strength of their candidacy, so we urge you not to exclude yourself prematurely and to submit an application if you're interested in this work. We think AI systems like the ones we're building have enormous social and ethical implications. We think this makes representation even more important, and we strive to include a range of diverse perspectives on our team.<br><br><strong data-stringify-type="bold">Your safety matters to us.</strong>&nbsp;To protect yourself from potential scams, remember that Anthropic recruiters only contact you from&nbsp;@anthropic.com&nbsp;email addresses. Be cautious of emails from other domains. Legitimate Anthropic recruiters will never ask for money, fees, or banking information before your first day. If you're ever unsure about a communication, don't click any links—visit&nbsp;<u data-stringify-type="underline"><a class="c-link c-link--underline" href="http://anthropic.com/careers" target="_blank" data-stringify-link="http://anthropic.com/careers" data-sk="tooltip_parent" data-remove-tab-index="true">anthropic.com/careers</a></u>&nbsp;directly for confirmed position openings.</p>
<h2><strong>How we're different</strong></h2>
<p>We believe that the highest-impact AI research will be big science. At Anthropic we work as a single cohesive team on just a few large-scale research efforts. And we value impact — advancing our long-term goals of steerable, trustworthy AI — rather than work on smaller and more specific puzzles. We view AI research as an empirical science, which has as much in common with physics and biology as with traditional efforts in computer science. We're an extremely collaborative group, and we host frequent research discussions to ensure that we are pursuing the highest-impact work at any given time. As such, we greatly value communication skills.</p>
<p>The easiest way to understand our research directions is to read our recent research. This research continues many of the directions our team worked on prior to Anthropic, including: GPT-3, Circuit-Based Interpretability, Multimodal Neurons, Scaling Laws, AI &amp; Compute, Concrete Problems in AI Safety, and Learning from Human Preferences.</p>
<h2><strong>Come work with us!</strong></h2>
<p>Anthropic is a public benefit corporation headquartered in San Francisco. We offer competitive compensation and benefits, optional equity donation matching, generous vacation and parental leave, flexible working hours, and a lovely office space in which to collaborate with colleagues. <strong data-stringify-type="bold">Guidance on Candidates' AI Usage:</strong>&nbsp;Learn about&nbsp;<a class="c-link" href="https://www.anthropic.com/candidate-ai-guidance" target="_blank" data-stringify-link="https://www.anthropic.com/candidate-ai-guidance" data-sk="tooltip_parent">our policy</a>&nbsp;for using AI in our application process</p></div>