<div class="content-intro"><h2><strong>About Anthropic</strong></h2>
<p>Anthropic’s mission is to create reliable, interpretable, and steerable AI systems. We want AI to be safe and beneficial for our users and for society as a whole. Our team is a quickly growing group of committed researchers, engineers, policy experts, and business leaders working together to build beneficial AI systems.</p></div><h2 class="heading"><strong>About the Role</strong></h2>
<p>You'll drive cross-functional execution of Anthropic's data center programs from construction through commissioning and day-to-day operations. Partnering with our Data Center and Compute teams, you'll own the program management that delivers buildings on time ready for production workloads. As we scale beyond our first sites, you'll focus on accelerating construction and deployment, building repeatable playbooks, and driving continuous improvement across our growing footprint.</p>
<h2 class="heading"><strong>Responsibilities:</strong></h2>
<ul>
<li>Manage and develop the DC infrastructure TPM team; hire and build out the function as we scale</li>
<li>Lead program reviews and executive communications on delivery status, risks, and blockers</li>
<li>Drive construction-to-production execution across multiple sites, coordinating with partners, contractors, and internal teams</li>
<li>Own overall schedule tracking, risk identification, and mitigation; creating clear visibility for leadership</li>
<li>Align with energy and location strategy and support site selection and due diligence criteria to facilitate scaling well in advance of aggressive compute demand</li>
<li>Manage long pole dependencies and long-lead time development &amp; procurement across a dynamically changing global marketplace</li>
<li>Partner with DC and Compute teams to drive handover criteria between site completion, equipment deployment, and operations</li>
<li>Coordinate with Infrastructure, Security, and Compliance teams on evolving requirements; versioning, optimization, and expansion across sites</li>
<li>Drive partner accountability on contractual milestones and commercial commitments</li>
<li>Coordinate equipment delivery and manage vendor accountability on schedules; tracking production and shipping milestones while maintaining productive partnerships</li>
<li>Build repeatable processes and playbooks that scale across multiple concurrent site deployments</li>
<li>Travel (20%) to sites to validate progress and build contractor relationships</li>
</ul>
<h2 class="heading"><strong>You may be a good fit if you:</strong></h2>
<ul>
<li>Have 7+ years in data center construction, operations, or infrastructure program management at hyperscale or critical infrastructure companies</li>
<li>Have management experience building and leading TPM or program management teams</li>
<li>Have led multi-site infrastructure programs with compressed timelines and complex cross-functional dependencies among multiple partners and vendors</li>
<li>Excel at aligning multiple partners, vendors, and internal engineering teams around shared deliverables</li>
<li>Can bridge physical infrastructure and software/security teams</li>
<li>Thrive in ambiguity and make decisions with incomplete information under schedule pressure</li>
<li>Communicate complex program status clearly to executives</li>
</ul>
<p><strong>Deadline to apply:</strong> None applications will be received on a rolling basis.</p><div class="content-pay-transparency"><div class="pay-input"><div class="description"><p>The annual compensation range for this role is below. For sales roles, the range provided is the role’s On Target Earnings ("OTE") range, meaning that the range includes both the sales commissions/sales bonuses target and annual base salary for the role. Our total compensation package for full-time employees includes equity and benefits.</p></div><div class="title">Annual Salary:</div><div class="pay-range"><span>$365,000</span><span class="divider">&mdash;</span><span>$435,000 USD</span></div></div></div><div class="content-conclusion"><h2><strong>Logistics</strong></h2>
<p><strong>Education requirements: </strong>We require at least a Bachelor's degree in a related field or equivalent experience.<strong><br><br>Location-based hybrid policy:</strong> Currently, we expect all staff to be in one of our offices at least 25% of the time. However, some roles may require more time in our offices.</p>
<p><strong data-stringify-type="bold">Visa sponsorship:</strong>&nbsp;We do sponsor visas! However, we aren't able to successfully sponsor visas for every role and every candidate. But if we make you an offer, we will make every reasonable effort to get you a visa, and we retain an immigration lawyer to help with this.</p>
<p><strong>We encourage you to apply even if you do not believe you meet every single qualification.</strong> Not all strong candidates will meet every single qualification as listed.&nbsp; Research shows that people who identify as being from underrepresented groups are more prone to experiencing imposter syndrome and doubting the strength of their candidacy, so we urge you not to exclude yourself prematurely and to submit an application if you're interested in this work. We think AI systems like the ones we're building have enormous social and ethical implications. We think this makes representation even more important, and we strive to include a range of diverse perspectives on our team.<br><br><strong data-stringify-type="bold">Your safety matters to us.</strong>&nbsp;To protect yourself from potential scams, remember that Anthropic recruiters only contact you from&nbsp;@anthropic.com&nbsp;email addresses. Be cautious of emails from other domains. Legitimate Anthropic recruiters will never ask for money, fees, or banking information before your first day. If you're ever unsure about a communication, don't click any links—visit&nbsp;<u data-stringify-type="underline"><a class="c-link c-link--underline" href="http://anthropic.com/careers" target="_blank" data-stringify-link="http://anthropic.com/careers" data-sk="tooltip_parent" data-remove-tab-index="true">anthropic.com/careers</a></u>&nbsp;directly for confirmed position openings.</p>
<h2><strong>How we're different</strong></h2>
<p>We believe that the highest-impact AI research will be big science. At Anthropic we work as a single cohesive team on just a few large-scale research efforts. And we value impact — advancing our long-term goals of steerable, trustworthy AI — rather than work on smaller and more specific puzzles. We view AI research as an empirical science, which has as much in common with physics and biology as with traditional efforts in computer science. We're an extremely collaborative group, and we host frequent research discussions to ensure that we are pursuing the highest-impact work at any given time. As such, we greatly value communication skills.</p>
<p>The easiest way to understand our research directions is to read our recent research. This research continues many of the directions our team worked on prior to Anthropic, including: GPT-3, Circuit-Based Interpretability, Multimodal Neurons, Scaling Laws, AI &amp; Compute, Concrete Problems in AI Safety, and Learning from Human Preferences.</p>
<h2><strong>Come work with us!</strong></h2>
<p>Anthropic is a public benefit corporation headquartered in San Francisco. We offer competitive compensation and benefits, optional equity donation matching, generous vacation and parental leave, flexible working hours, and a lovely office space in which to collaborate with colleagues. <strong data-stringify-type="bold">Guidance on Candidates' AI Usage:</strong>&nbsp;Learn about&nbsp;<a class="c-link" href="https://www.anthropic.com/candidate-ai-guidance" target="_blank" data-stringify-link="https://www.anthropic.com/candidate-ai-guidance" data-sk="tooltip_parent">our policy</a>&nbsp;for using AI in our application process</p></div>